// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/weather/v1/weather.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float32 `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon float32 `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *GetWeatherRequest) Reset() {
	*x = GetWeatherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_v1_weather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherRequest) ProtoMessage() {}

func (x *GetWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_v1_weather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherRequest) Descriptor() ([]byte, []int) {
	return file_api_weather_v1_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeatherRequest) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetWeatherRequest) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type GetWeatherReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data        *GetWeatherReply_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Temperature float32               `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (x *GetWeatherReply) Reset() {
	*x = GetWeatherReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_v1_weather_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherReply) ProtoMessage() {}

func (x *GetWeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_v1_weather_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherReply.ProtoReflect.Descriptor instead.
func (*GetWeatherReply) Descriptor() ([]byte, []int) {
	return file_api_weather_v1_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherReply) GetData() *GetWeatherReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetWeatherReply) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type GetWeatherReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *GetWeatherReply_Data) Reset() {
	*x = GetWeatherReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_v1_weather_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherReply_Data) ProtoMessage() {}

func (x *GetWeatherReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_v1_weather_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherReply_Data.ProtoReflect.Descriptor instead.
func (*GetWeatherReply_Data) Descriptor() ([]byte, []int) {
	return file_api_weather_v1_weather_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetWeatherReply_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetWeatherReply_Data) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_weather_v1_weather_proto protoreflect.FileDescriptor

var file_api_weather_v1_weather_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x37,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x22, 0xab, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x57,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x3c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x5b, 0x0a, 0x07, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x12, 0x50, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x21,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x35, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x21, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_weather_v1_weather_proto_rawDescOnce sync.Once
	file_api_weather_v1_weather_proto_rawDescData = file_api_weather_v1_weather_proto_rawDesc
)

func file_api_weather_v1_weather_proto_rawDescGZIP() []byte {
	file_api_weather_v1_weather_proto_rawDescOnce.Do(func() {
		file_api_weather_v1_weather_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_weather_v1_weather_proto_rawDescData)
	})
	return file_api_weather_v1_weather_proto_rawDescData
}

var file_api_weather_v1_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_weather_v1_weather_proto_goTypes = []interface{}{
	(*GetWeatherRequest)(nil),    // 0: api.weather.v1.GetWeatherRequest
	(*GetWeatherReply)(nil),      // 1: api.weather.v1.GetWeatherReply
	(*GetWeatherReply_Data)(nil), // 2: api.weather.v1.GetWeatherReply.Data
}
var file_api_weather_v1_weather_proto_depIdxs = []int32{
	2, // 0: api.weather.v1.GetWeatherReply.data:type_name -> api.weather.v1.GetWeatherReply.Data
	0, // 1: api.weather.v1.Weather.GetWeather:input_type -> api.weather.v1.GetWeatherRequest
	1, // 2: api.weather.v1.Weather.GetWeather:output_type -> api.weather.v1.GetWeatherReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_weather_v1_weather_proto_init() }
func file_api_weather_v1_weather_proto_init() {
	if File_api_weather_v1_weather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_weather_v1_weather_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_v1_weather_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_v1_weather_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_weather_v1_weather_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_weather_v1_weather_proto_goTypes,
		DependencyIndexes: file_api_weather_v1_weather_proto_depIdxs,
		MessageInfos:      file_api_weather_v1_weather_proto_msgTypes,
	}.Build()
	File_api_weather_v1_weather_proto = out.File
	file_api_weather_v1_weather_proto_rawDesc = nil
	file_api_weather_v1_weather_proto_goTypes = nil
	file_api_weather_v1_weather_proto_depIdxs = nil
}
